window.SBO_BOSS_DATA = {
  bosses: [
    {
      id: "illfang",
      name: "Illfang the Kobold Lord",
      wikiUrl: "https://swordbloxonlinerebirth.fandom.com/wiki/Illfang_The_Kobold_Lord",
      floor: 2,
      recLevel: 10,
      recSkill: 60,
      hp: 20000,
      exp: 1800,
      col: 240,
      statusEffect: null,
      phases: [
        { hpThresholdPct: 100, name: "Axe & Shield", notes: "Blocks frequently. Attack from the side." },
        { hpThresholdPct: 33,  name: "Nodachi", notes: "Drops shield, gains wide sweeping attacks. Stay mobile." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Iron Ore", "Copper Ore"],
      rareDrops: ["Illfangs Tooth", "Illfangs Shield"],
      lastHitDrop: "Coat of Midnight",
      location: "Floor 2 — Boss Room: Illfang's Throne Room",
      respawnTime: "180 seconds",
      notes: "Floor 2 boss. Recommended to fight in a group. Adds spawn at each HP bar.",
      exactStats: true,
    },
    {
      id: "lord-slug",
      name: "Lord Slug",
      wikiUrl: "https://swordbloxonlinerebirth.fandom.com/wiki/Lord_Slug",
      floor: 3,
      recLevel: 20,
      recSkill: 60,
      hp: 38000,
      exp: 3600,
      col: 480,
      statusEffect: "Poison (chance)",
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Hitbox is deceptive — can hit from unexpected range. Safe spot on stairs." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Malachite Ore", "Corundum Ore"],
      rareDrops: ["Legendary Malachite Blade", "Lord Slugs Slime"],
      lastHitDrop: null,
      location: "Floor 3 — Dungeon Boss Room",
      respawnTime: "180 seconds",
      notes: "Floor 3 dungeon boss. Easier than Illfang — can be safely attacked from the stairs. Hitbox is buggy; watch your positioning.",
      exactStats: true,
    },
    {
      id: "stallord",
      name: "Stallord",
      wikiUrl: "https://swordbloxonlinerebirth.fandom.com/wiki/Stallord",
      floor: 4,
      recLevel: 30,
      recSkill: 80,
      hp: 61000,
      exp: 5400,
      col: 720,
      statusEffect: null,
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Aggressive melee attacks. Stay mobile and punish openings." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Gold Ore"],
      rareDrops: ["Stallords Eye", "Pharaoh's Edge"],
      lastHitDrop: null,
      location: "Floor 4 — Boss Room",
      respawnTime: "180 seconds",
      notes: "Floor 4 boss. Straightforward fight — good for farming Gold Ore.",
      exactStats: true,
    },
    {
      id: "x-rphan",
      name: "X'rphan the White Wyrm",
      wikiUrl: "https://swordbloxonlinerebirth.fandom.com/wiki/X%27rphan_the_White_Wyrm",
      floor: 5,
      recLevel: 40,
      recSkill: 100,
      hp: 86000,
      exp: 7200,
      col: 960,
      statusEffect: "Freeze (chance)",
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Freeze can lock you in place — keep moving. High AGI reduces freeze windows." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Bourne Ore"],
      rareDrops: ["Xrphans Feather", "Auroras Cloak"],
      lastHitDrop: null,
      location: "Floor 5 — Boss Room",
      respawnTime: "180 seconds",
      notes: "Floor 5 boss. Freeze status effect — VIT-based debuff resistance helps. High AGI keeps you mobile.",
      exactStats: true,
    },
    {
      id: "uakmaroth",
      name: "Uakmaroth, the Demon Lord",
      wikiUrl: "https://swordbloxonlinerebirth.fandom.com/wiki/Uakmaroth,_the_Demon_Lord",
      floor: 6,
      recLevel: 50,
      recSkill: 120,
      hp: 114000,
      exp: 9000,
      col: 1200,
      statusEffect: "On Fire",
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Inflicts Burn on hit. VIT-based debuff resistance reduces duration." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Demonite"],
      rareDrops: ["Uakmaroths Horn", "Yukkis Mourne"],
      lastHitDrop: null,
      location: "Floor 6 — Boss Room: Uakmaroth's Chamber",
      respawnTime: "180 seconds",
      notes: "Floor 6 boss. Burn status effect — keep debuff resistance (VIT) in mind. Demonite is a key crafting material.",
      exactStats: true,
    },
    {
      id: "storm-atronach",
      name: "Storm Atronach",
      wikiUrl: "https://swordbloxonlinerebirth.fandom.com/wiki/Storm_Atronach",
      floor: 7,
      recLevel: 60,
      recSkill: 140,
      hp: 144000,
      exp: 10800,
      col: 1440,
      statusEffect: "Paralysis (chance)",
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Paralysis can stop you cold. High VIT reduces proc chance and duration." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Angels Dust"],
      rareDrops: ["Stone Armor", "The Green Flame Sword", "Plasma Extract"],
      lastHitDrop: null,
      location: "Floor 7 — Boss Room",
      respawnTime: "180 seconds",
      notes: "Floor 7 boss. Paralysis is dangerous — prioritize VIT for debuff resistance. Green Flame Sword is a notable rare drop.",
      exactStats: true,
    },
    {
      id: "bonnz",
      name: "Bonnz the Skeleton Lord",
      wikiUrl: "https://swordbloxonlinerebirth.fandom.com/wiki/Bonnz_the_Skeleton_Lord",
      floor: 8,
      recLevel: 70,
      recSkill: 160,
      hp: 177000,
      exp: 12600,
      col: 1680,
      statusEffect: "Bleeding",
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Spacious boss room with Shadow Walkers around the perimeter. Focus the boss." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Bone Meal", "Ebony Ore"],
      rareDrops: ["Skull of the Forgotten", "Petrified Skull", "Stone Shield"],
      lastHitDrop: null,
      location: "Floor 8 — Boss Room",
      respawnTime: "180 seconds",
      notes: "Floor 8 boss. Inflicts Bleeding — keep HP high. Many players are over-levelled here from dungeon farming.",
      exactStats: true,
    },
    {
      id: "karth-uk",
      name: "Karth'uk the Crystal Kraken",
      wikiUrl: "https://swordbloxonlinerebirth.fandom.com/wiki/Karth%27uk_The_Crystal_Kraken",
      floor: 9,
      recLevel: 80,
      recSkill: 180,
      hp: 210000,
      exp: 14400,
      col: 7200,
      statusEffect: "Poison",
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Poison on hit — VIT debuff resistance reduces duration. High Col reward." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Scale", "Sea Jewel"],
      rareDrops: ["Krakens Beak", "Krakens Skin", "Krakens Platemail"],
      lastHitDrop: null,
      location: "Floor 9 — Boss Room",
      respawnTime: "180 seconds",
      notes: "Floor 9 boss. Highest Col reward of any boss at this tier (7,200). Poison status — VIT helps.",
      exactStats: true,
    },
    {
      id: "hotoke",
      name: "Hotoke the Enlightened",
      wikiUrl: "https://swordbloxonlinerebirth.fandom.com/wiki/Hotoke_The_Enlightened",
      floor: 10,
      recLevel: 90,
      recSkill: 200,
      hp: 246000,
      exp: 16200,
      col: 2160,
      statusEffect: null,
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "No status effect. Pure damage and survivability check." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: [],
      rareDrops: ["Monks Sash", "Yang Katana"],
      lastHitDrop: null,
      location: "Floor 10 — Boss Room",
      respawnTime: "180 seconds",
      notes: "Floor 10 boss. No status effects — straightforward DPS and survivability check. Yang Katana is a strong rare drop.",
      exactStats: true,
    },
    {
      id: "grimlock",
      name: "Grimlock the Fallen King",
      wikiUrl: "https://swordbloxonlinerebirth.fandom.com/wiki/Grimlock_the_Fallen_King",
      floor: 11,
      recLevel: 100,
      recSkill: 220,
      hp: 264000,
      exp: 18000,
      col: 2400,
      statusEffect: "Burn",
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Inflicts Burn. VIT debuff resistance reduces duration. Watch for combo windows." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Corruption Tendrils", "Harrowed Ore"],
      rareDrops: ["Kings Crown", "Vehement Resistance", "Whale"],
      lastHitDrop: null,
      location: "Floor 11 — Boss Room",
      respawnTime: "180 seconds",
      notes: "Floor 11 boss. Burn status — keep debuff resistance up. Kings Crown and Vehement Resistance are strong rare drops.",
      exactStats: true,
    },
    {
      id: "laurellis",
      name: "Laurellis the Purgatory Flax",
      floor: 12,
      recLevel: 110,
      recSkill: 240,
      hp: 321000,
      exp: 19800,
      col: 2640,
      statusEffect: "Poison",
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Poison on hit. High VIT and bonusHP recommended for sustained fights." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Plant Matter"],
      rareDrops: ["Queens Vine", "Eternity Branches"],
      lastHitDrop: null,
      location: "Floor 12 — Boss Room",
      respawnTime: "Unknown",
      estimateNote: "HP, EXP, Col, respawn time unconfirmed — wiki page returns no content. Values estimated.",
      notes: "Floor 12 boss. Poison status — VIT debuff resistance is key. Shares floor with Slime Lord Pengonis.",
      exactStats: false,
    },
    {
      id: "slime-lord-pengonis",
      name: "Slime Lord Pengonis",
      wikiUrl: "https://swordbloxonlinerebirth.fandom.com/wiki/Slime_Lord_Pengonis",
      floor: 12,
      recLevel: 110,
      recSkill: 240,
      hp: 321000,
      exp: 19800,
      col: 2640,
      statusEffect: "Poison",
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Poison on hit. Appeared while Laurellis was absent from her domain." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Plant Matter"],
      rareDrops: ["Queens Vine", "Eternity Branches"],
      lastHitDrop: null,
      location: "Floor 12 — Boss Room (alternate)",
      respawnTime: "180 seconds",
      notes: "Floor 12 alternate boss — appeared while Laurellis was absent. Same stats and drops. Poison status — VIT helps.",
      exactStats: true,
    },
    {
      id: "tormented-soul",
      name: "The Tormented Soul",
      wikiUrl: "https://swordbloxonlinerebirth.fandom.com/wiki/The_Tormented_Soul",
      floor: 13,
      recLevel: 120,
      recSkill: 260,
      hp: 361000,
      exp: 21600,
      col: 2880,
      statusEffect: null,
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "No status effect. Pure DPS and survivability fight." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Dark Matter"],
      rareDrops: ["Soul", "Peaceful Rest", "Hope Blade", "Hope Dagger", "Hope Rapier", "Hope Buster"],
      lastHitDrop: null,
      location: "Floor 13 — Boss Room",
      respawnTime: "180 seconds",
      notes: "Floor 13 boss. No status effects. Large rare drop pool — Hope weapons are notable. High sustained DPS required.",
      exactStats: true,
    },
    {
      id: "young-celestia",
      name: "Young Celestia",
      wikiUrl: "https://swordbloxonlinerebirth.fandom.com/wiki/Young_Celestia",
      floor: 14,
      recLevel: 135,
      recSkill: 280,
      hp: 423000,
      exp: 24300,
      col: 3240,
      statusEffect: "Paralysis",
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Paralysis on hit — extremely dangerous. Max VIT debuff resistance recommended." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: [],
      rareDrops: ["Das Chaos", "Die Vergangenheit", "Der Zerstorer", "Die Klarheit"],
      lastHitDrop: "Divine Guard",
      location: "Floor 14 — Boss Room",
      respawnTime: "3 minutes",
      notes: "Floor 14 boss. Paralysis is the most dangerous status — high VIT essential. Last hit drops Divine Guard.",
      exactStats: true,
    },
    {
      id: "two-headed-giant",
      name: "Two-Headed Giant",
      wikiUrl: "https://swordbloxonlinerebirth.fandom.com/wiki/Two-Headed_Giant",
      floor: 16,
      recLevel: 160,
      recSkill: 340,
      hp: 531000,
      exp: 28800,
      col: 3040,
      statusEffect: "Bleed",
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Normal weapons are ineffective — requires a weapon that can steal Sacred Resources." },
        { hpThresholdPct: 50,  name: "Bleed Phase", notes: "Gains ability to inflict Bleed. Keep HP topped up." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: [],
      rareDrops: ["Giant Chains", "Giant Hammer", "Two-Headed Soul", "Two-Headed Cape"],
      lastHitDrop: null,
      location: "Floor 16 — Boss Room",
      respawnTime: "3 minutes",
      notes: "Floor 16 boss. Requires a Sacred Resource-stealing weapon — normal weapons won't work. Gains Bleed in phase 2.",
      exactStats: true,
    },
    {
      id: "captain-sweet",
      name: "Captain Sweet the Forever Child",
      wikiUrl: "https://swordbloxonlinerebirth.fandom.com/wiki/Captain_Sweet_the_Forever_Child",
      floor: 17,
      recLevel: 168,
      recSkill: 360,
      hp: 567000,
      exp: 30600,
      col: 4080,
      statusEffect: "Paralysis (chance)",
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Can inflict Paralysis. Found in the Candy Castle on Floor 17." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Sweet Candy"],
      rareDrops: ["Captains Tooth", "Candy Soldier Hat", "Candy Soldier Uniform"],
      lastHitDrop: null,
      location: "Floor 17 — Candy Castle",
      respawnTime: "3 minutes",
      notes: "Floor 17 boss. Can inflict Paralysis — high VIT recommended. Found locked up inside the Candy Castle.",
      exactStats: true,
    },
    {
      id: "frontman",
      name: "The Frontman",
      wikiUrl: "https://swordbloxonlinerebirth.fandom.com/wiki/The_Frontman",
      floor: 18,
      recLevel: 200,
      recSkill: 400,
      hp: 1256500,
      exp: 36000,
      col: 4800,
      statusEffect: null,
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Highest HP boss in the game. Unique fighting style learned from watching players. Full party required." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Black Tag", "Control Chip", "Protocol Shard"],
      rareDrops: [],
      lastHitDrop: null,
      location: "Floor 18 — The Arena",
      respawnTime: "5 minutes",
      notes: "Floor 18 final boss. Highest HP in the game at 1,256,500. Unique moveset adapted from watching players fight.",
      exactStats: true,
    },
    {
      id: "eidolon",
      name: "Eidolon the Gilded Omen",
      wikiUrl: "https://swordbloxonlinerebirth.fandom.com/wiki/Eidolon_the_Gilded_Omen",
      floor: 18,
      recLevel: 190,
      recSkill: 380,
      hp: 670000,
      exp: 34200,
      col: 4560,
      statusEffect: "Bleed",
      phases: [
        { hpThresholdPct: 100, name: "Gilded Form", notes: "Can inflict Bleed. High bonusHP and damage reduction required." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Echo Residue", "Gilded Plate Fragment", "Legacy Core"],
      rareDrops: [],
      lastHitDrop: null,
      location: "Floor 18 — Boss Room",
      respawnTime: "3 minutes",
      notes: "Floor 18 boss. Can inflict Bleed. Full party strongly recommended.",
      exactStats: true,
    },
  ],

  miniBosses: [
    {
      id: "shadesworn",
      name: "Shadesworn the Corrupted",
      floor: 2,
      type: "mini",
      recLevel: 6,
      recSkill: 30,
      hp: 14000,
      exp: 1080,
      col: 144,
      statusEffect: "On Fire (chance)",
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Found in the Underground Dungeon on Floor 2. Can inflict On Fire." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: [],
      rareDrops: ["Obsidibite", "GrandMaster Shield"],
      lastHitDrop: null,
      location: "Floor 2 — The Underground Dungeon",
      respawnTime: "2 minutes",
      notes: "Floor 2 mini boss found in the Underground Dungeon. Drops GrandMaster Shield — a useful early shield.",
      exactStats: true,
    },
    {
      id: "father-shroom",
      name: "Father Shroom",
      floor: 7,
      type: "mini",
      recLevel: 55,
      recSkill: 140,
      hp: 129000,
      exp: 9900,
      col: 1320,
      statusEffect: null,
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Found in the Floor 7 Miniboss Cave. No status effect." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Shiek Greatsword"],
      rareDrops: [],
      lastHitDrop: null,
      location: "Floor 7 — Miniboss Cave",
      respawnTime: "300 seconds",
      estimateNote: "recSkill is estimated — wiki lists Skill Level Cap 120, not a recommended skill.",
      notes: "Floor 7 mini boss. Drops the Shiek Greatsword directly — a notable two-handed weapon.",
      exactStats: true,
    },
    {
      id: "guardian-of-the-gate",
      name: "Guardian of the Gate",
      floor: 9,
      type: "mini",
      recLevel: 75,
      recSkill: 180,
      hp: 193000,
      exp: 13500,
      col: 1800,
      statusEffect: null,
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Found in the Floor 9 Miniboss Chamber." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Scale", "Coral"],
      rareDrops: ["Poseidons Trident"],
      lastHitDrop: null,
      location: "Floor 9 — Miniboss Chamber",
      respawnTime: "180 seconds",
      notes: "Floor 9 mini boss. Poseidon's Trident is a notable rare drop. Good Col reward.",
      exactStats: true,
    },
    {
      id: "laurellis-convict",
      name: "Laurellis Convict",
      floor: 12,
      type: "mini",
      recLevel: 105,
      recSkill: 240,
      hp: 300000,
      exp: 18900,
      col: 2520,
      statusEffect: null,
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Found in the Floor 12 Miniboss Chamber." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Plant Matter"],
      rareDrops: ["Trunk Destroyer", "Harmony Renaissance", "Oak Wood"],
      lastHitDrop: null,
      location: "Floor 12 — Miniboss Chamber",
      respawnTime: "180 seconds",
      notes: "Floor 12 mini boss. Strong rare drop pool — Trunk Destroyer and Harmony Renaissance are notable weapons.",
      exactStats: true,
    },
    {
      id: "tormented-spectrum",
      name: "Tormented Spectrum",
      floor: 13,
      type: "mini",
      recLevel: 110,
      recSkill: 260,
      hp: 321000,
      exp: 19800,
      col: 2640,
      statusEffect: "Decay",
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Found in the Floor 13 Miniboss Chamber. Inflicts Decay." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Dark Matter"],
      rareDrops: ["Cursed Shield", "Cursed Buster"],
      lastHitDrop: null,
      location: "Floor 13 — Miniboss Chamber",
      respawnTime: "180 seconds",
      notes: "Floor 13 mini boss. Inflicts Decay — a dangerous status. Cursed Shield and Cursed Buster are notable drops.",
      exactStats: true,
    },
    {
      id: "elder-celatid",
      name: "Elder Celatid",
      floor: 14,
      type: "mini",
      recLevel: 130,
      recSkill: 280,
      hp: 402000,
      exp: 23400,
      col: 3120,
      statusEffect: "Poison",
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Found on Floor 14. Inflicts Poison. Drops Heavenly Ore." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Heavenly Ore"],
      rareDrops: [],
      lastHitDrop: null,
      location: "Floor 14",
      respawnTime: "3 minutes",
      notes: "Floor 14 mini boss. Inflicts Poison. Drops Heavenly Ore (0–3) — a key crafting material.",
      exactStats: true,
    },
    {
      id: "beatrice",
      name: "Beatrice the Impartial Queen",
      floor: 11,
      type: "mini",
      recLevel: 100,
      recSkill: 220,
      hp: 264000,
      exp: 17100,
      col: 2280,
      statusEffect: null,
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Found at the Floor 11 Dungeon Entrance." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Corruption Tendrils", "Harrowed Ore"],
      rareDrops: ["Queens Resolve", "Impurity"],
      lastHitDrop: null,
      location: "Floor 11 — Dungeon Entrance",
      respawnTime: "180 seconds",
      notes: "Floor 11 mini boss at the dungeon entrance. Queens Resolve and Impurity are notable rare drops.",
      exactStats: true,
    },
    {
      id: "buffed-knight",
      name: "Buffed Knight",
      floor: 11,
      type: "mini",
      recLevel: 100,
      recSkill: 220,
      hp: 264000,
      exp: 18000,
      col: 2400,
      statusEffect: null,
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Found at the Floor 11 Dungeon Entrance alongside Beatrice." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Harrowed Ore"],
      rareDrops: ["Queens Resolve", "Impurity"],
      lastHitDrop: null,
      location: "Floor 11 — Dungeon Entrance",
      respawnTime: "180 seconds",
      notes: "Floor 11 mini boss at the dungeon entrance. Shares rare drops with Beatrice the Impartial Queen.",
      exactStats: true,
    },
    {
      id: "leader-grimm",
      name: "Leader Grimm",
      floor: 14,
      type: "mini",
      recLevel: 120,
      recSkill: 280,
      hp: 361000,
      exp: 21600,
      col: 2880,
      statusEffect: "Freeze",
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Found on Floor 14. Inflicts Freeze — high VIT recommended." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: [],
      rareDrops: ["Corrupted Sky"],
      lastHitDrop: null,
      location: "Floor 14",
      respawnTime: "3 minutes",
      notes: "Floor 14 mini boss. Inflicts Freeze. Corrupted Sky is the notable rare drop.",
      exactStats: true,
    },
    {
      id: "leader-goblin",
      name: "Leader Goblin",
      floor: 16,
      type: "mini",
      recLevel: 160,
      recSkill: 340,
      hp: 531000,
      exp: 28800,
      col: 3040,
      statusEffect: "Poison",
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Found on Floor 16. Inflicts Poison. Same HP as Two-Headed Giant." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: [],
      rareDrops: ["Poisonous Cleaver", "Goblin Garments"],
      lastHitDrop: null,
      location: "Floor 16",
      respawnTime: "3 minutes",
      notes: "Floor 16 mini boss. Inflicts Poison. Poisonous Cleaver and Goblin Garments are the rare drops.",
      exactStats: true,
    },
    {
      id: "super-luo",
      name: "Super Luo",
      wikiUrl: "https://swordbloxonlinerebirth.fandom.com/wiki/Super_Luo",
      floor: 14,
      type: "mini",
      recLevel: 125,
      recSkill: 280,
      hp: 381000,
      exp: 22500,
      col: 3000,
      statusEffect: "Paralysis",
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "2nd of 3 Floor 14 mini bosses. Found on the second cluster. Inflicts Paralysis." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Heavenly Ore"],
      rareDrops: ["Holy Light Dagger"],
      lastHitDrop: null,
      location: "Floor 14 — Second Cluster",
      respawnTime: "3 minutes",
      notes: "Floor 14 mini boss. Inflicts Paralysis — high VIT recommended. Holy Light Dagger is the notable rare drop.",
      exactStats: true,
    },
    {
      id: "thug-boss",
      name: "Thug Boss",
      wikiUrl: "https://swordbloxonlinerebirth.fandom.com/wiki/Thug_Boss",
      floor: 18,
      type: "mini",
      recLevel: 177,
      recSkill: 380,
      hp: 609000,
      exp: 31860,
      col: 4248,
      statusEffect: null,
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Leader of the Neon District thugs. No status effect." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: [],
      rareDrops: [],
      lastHitDrop: null,
      location: "Floor 18 — Neon District",
      respawnTime: "5 minutes",
      notes: "Floor 18 mini boss. Leader of the thugs in the Neon District. No notable drops.",
      exactStats: true,
    },
    {
      id: "loan-shark-boss",
      name: "Loan Shark Boss",
      wikiUrl: "https://swordbloxonlinerebirth.fandom.com/wiki/Loan_Shark_Boss",
      floor: 18,
      type: "mini",
      recLevel: 180,
      recSkill: 380,
      hp: 623000,
      exp: 32400,
      col: 4320,
      statusEffect: "Bleed (chance)",
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Leader of the Warehouse District Loan Sharks. Can inflict Bleed." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["City Enforcement Core", "Knuckle Guard", "Loan Shark Contract"],
      rareDrops: ["Heavy Ledger Coat"],
      lastHitDrop: null,
      location: "Floor 18 — Warehouse District",
      respawnTime: "3 minutes",
      notes: "Floor 18 mini boss. Can inflict Bleed. Heavy Ledger Coat is the notable rare drop.",
      exactStats: true,
    },
    {
      id: "the-custodian",
      name: "The Custodian",
      wikiUrl: "https://swordbloxonlinerebirth.fandom.com/wiki/The_Custodian",
      floor: 18,
      type: "mini",
      recLevel: 185,
      recSkill: 380,
      hp: 646000,
      exp: 33300,
      col: 4440,
      statusEffect: "Freeze (chance)",
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "The Frontman's cleaner. Can inflict Freeze." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Pale Veil Fragment", "Wraith Bone Shard"],
      rareDrops: ["Marble Core", "Custodian Mask", "Redline Lace", "Failshard"],
      lastHitDrop: null,
      location: "Floor 18 — The Squid Game",
      respawnTime: "3 minutes",
      notes: "Floor 18 mini boss hired by The Frontman. Can inflict Freeze — VIT recommended. Strong rare drop pool.",
      exactStats: true,
    },
    {
      id: "the-arbitrator",
      name: "The Arbitrator",
      wikiUrl: "https://swordbloxonlinerebirth.fandom.com/wiki/The_Arbitrator",
      floor: 18,
      type: "mini",
      recLevel: 190,
      recSkill: 380,
      hp: 670000,
      exp: 34200,
      col: 4560,
      statusEffect: "Bleed (chance)",
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "The Frontman's most trusted manager. Can inflict Bleed. High damage." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: ["Arbitrators Insignia", "Cracked Authority Mask", "Game Ticket", "Pentathlon Drive"],
      rareDrops: ["Redline Protocol", "Gamebreaker Greatsword"],
      lastHitDrop: null,
      location: "Floor 18 — The Squid Game",
      respawnTime: "3 minutes",
      notes: "Floor 18 mini boss — The Frontman's right hand. Gamebreaker Greatsword is a notable rare drop.",
      exactStats: true,
    },
    {
      id: "rejected",
      name: "Rejected",
      wikiUrl: "https://swordbloxonlinerebirth.fandom.com/wiki/Rejected",
      floor: 18,
      type: "mini",
      recLevel: 0,
      recSkill: 0,
      hp: 0,
      exp: 0,
      col: 0,
      statusEffect: "Bleed (chance)",
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "Experimental prototype guard. Can become invulnerable. Flee if encountered unprepared." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: [],
      rareDrops: [],
      lastHitDrop: null,
      location: "Floor 18 — The Squid Game",
      respawnTime: "Unknown",
      estimateNote: "All stats unknown — wiki lists ??? for all values. This boss is experimental and may have invulnerability phases.",
      notes: "Floor 18 experimental mini boss. Stats completely unknown. Can inflict Bleed and has invulnerability. Avoid unless fully prepared.",
      exactStats: false,
    },
    {
      id: "golgorossa",
      name: "Golgorossa",
      floor: 0,
      type: "mini",
      recLevel: 0,
      recSkill: 0,
      hp: 0,
      exp: 0,
      col: 0,
      statusEffect: null,
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "No wiki data available yet." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: [],
      rareDrops: [],
      lastHitDrop: null,
      location: "Unknown",
      respawnTime: "Unknown",
      notes: "Mini boss — no wiki data available yet.",
      exactStats: false,
    },
    {
      id: "raws",
      name: "Raws",
      floor: 0,
      type: "mini",
      recLevel: 0,
      recSkill: 0,
      hp: 0,
      exp: 0,
      col: 0,
      statusEffect: null,
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "No wiki data available yet." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: [],
      rareDrops: [],
      lastHitDrop: null,
      location: "Unknown",
      respawnTime: "Unknown",
      notes: "Mini boss — no wiki data available yet.",
      exactStats: false,
    },
    {
      id: "sortnena",
      name: "SortNena",
      floor: 0,
      type: "mini",
      recLevel: 0,
      recSkill: 0,
      hp: 0,
      exp: 0,
      col: 0,
      statusEffect: null,
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "No wiki data available yet." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: [],
      rareDrops: [],
      lastHitDrop: null,
      location: "Unknown",
      respawnTime: "Unknown",
      notes: "Mini boss — no wiki data available yet.",
      exactStats: false,
    },
    {
      id: "super-laz",
      name: "Super Laz",
      floor: 0,
      type: "mini",
      recLevel: 0,
      recSkill: 0,
      hp: 0,
      exp: 0,
      col: 0,
      statusEffect: null,
      phases: [
        { hpThresholdPct: 100, name: "Normal", notes: "No wiki data available yet." },
      ],
      resistances: { slash: 0, pierce: 0, blunt: 0 },
      weaknesses: [],
      drops: [],
      rareDrops: [],
      lastHitDrop: null,
      location: "Unknown",
      respawnTime: "Unknown",
      notes: "Mini boss — no wiki data available yet.",
      exactStats: false,
    },
  ],
};
