echo ">>> Command: dir /s /b "sbo-rebirth-planner\supabase\functions\sbo-ai-advisor\index.ts""
dir /s /b "sbo-rebirth-planner\supabase\functions\sbo-ai-advisor\index.ts"
echo "Exit Code: $?"
echo ""
echo ">>> Command: dir /s /b "sbo-rebirth-planner\app.js""
dir /s /b "sbo-rebirth-planner\app.js"
echo "Exit Code: $?"
echo ""
echo ">>> Command: dir /s /b "sbo-rebirth-planner\config.js""
dir /s /b "sbo-rebirth-planner\config.js"
echo "Exit Code: $?"
echo ""
echo ">>> Command: python -c "import os; content = open('sbo-rebirth-planner/supabase/functions/sbo-ai-advisor/index.ts', 'r').read(); print(content)""
python -c "import os; content = open('sbo-rebirth-planner/supabase/functions/sbo-ai-advisor/index.ts', 'r').read(); print(content)"
echo "Exit Code: $?"
echo ""
echo ">>> Command: python -c "import os; content = open('sbo-rebirth-planner/config.js', 'r').read(); print(content)""
python -c "import os; content = open('sbo-rebirth-planner/config.js', 'r').read(); print(content)"
echo "Exit Code: $?"
echo ""
echo ">>> Command: python -c "import os; content = open('sbo-rebirth-planner/app.js', 'r').read(); print(content)""
python -c "import os; content = open('sbo-rebirth-planner/app.js', 'r').read(); print(content)"
echo "Exit Code: $?"
echo ""
echo ">>> Command: python -c "import os; content = open('sbo-rebirth-planner/test_edge_function.js', 'r').read(); print(content)""
python -c "import os; content = open('sbo-rebirth-planner/test_edge_function.js', 'r').read(); print(content)"
echo "Exit Code: $?"
echo ""