echo ">>> Command: python -c "print(open('sbo-rebirth-planner/app.js', 'r', encoding='utf-8').read())""
python -c "print(open('sbo-rebirth-planner/app.js', 'r', encoding='utf-8').read())"
echo "Exit Code: $?"
echo ""
echo ">>> Command: dir /b sbo-rebirth-planner\*.html"
dir /b sbo-rebirth-planner\*.html
echo "Exit Code: $?"
echo ""
echo ">>> Command: python -c "print(open('sbo-rebirth-planner/index.html', 'r', encoding='utf-8').read())""
python -c "print(open('sbo-rebirth-planner/index.html', 'r', encoding='utf-8').read())"
echo "Exit Code: $?"
echo ""
echo ">>> Command: dir /b sbo-rebirth-planner\netlify.toml"
dir /b sbo-rebirth-planner\netlify.toml
echo "Exit Code: $?"
echo ""
echo ">>> Command: python -c "import os; print(os.path.exists('sbo-rebirth-planner/netlify.toml'))""
python -c "import os; print(os.path.exists('sbo-rebirth-planner/netlify.toml'))"
echo "Exit Code: $?"
echo ""
echo ">>> Command: type sbo-rebirth-planner\AI_SETUP.md"
type sbo-rebirth-planner\AI_SETUP.md
echo "Exit Code: $?"
echo ""