echo ">>> Command: python -c "import sys; print(open('sbo-rebirth-planner/app.js', 'r', encoding='utf-8').read().encode('ascii', 'ignore').decode('ascii'))""
python -c "import sys; print(open('sbo-rebirth-planner/app.js', 'r', encoding='utf-8').read().encode('ascii', 'ignore').decode('ascii'))"
echo "Exit Code: $?"
echo ""
echo ">>> Command: python -c "import sys; print(open('sbo-rebirth-planner/index.html', 'r', encoding='utf-8').read().encode('ascii', 'ignore').decode('ascii'))""
python -c "import sys; print(open('sbo-rebirth-planner/index.html', 'r', encoding='utf-8').read().encode('ascii', 'ignore').decode('ascii'))"
echo "Exit Code: $?"
echo ""
echo ">>> Command: python -c "print(open('sbo-rebirth-planner/netlify.toml', 'r').read())""
python -c "print(open('sbo-rebirth-planner/netlify.toml', 'r').read())"
echo "Exit Code: $?"
echo ""
echo ">>> Command: dir /s /b sbo-rebirth-planner\test_frontend_context.js"
dir /s /b sbo-rebirth-planner\test_frontend_context.js
echo "Exit Code: $?"
echo ""
echo ">>> Command: python -c "print(open('sbo-rebirth-planner/test_frontend_context.js', 'r', encoding='utf-8').read().encode('ascii', 'ignore').decode('ascii'))""
python -c "print(open('sbo-rebirth-planner/test_frontend_context.js', 'r', encoding='utf-8').read().encode('ascii', 'ignore').decode('ascii'))"
echo "Exit Code: $?"
echo ""