echo ">>> Command: cat "sbo-rebirth-planner/supabase/functions/sbo-ai-advisor/index.ts""
cat "sbo-rebirth-planner/supabase/functions/sbo-ai-advisor/index.ts"
echo "Exit Code: $?"
echo ""
echo ">>> Command: cat "sbo-rebirth-planner/app.js""
cat "sbo-rebirth-planner/app.js"
echo "Exit Code: $?"
echo ""
echo ">>> Command: cat "sbo-rebirth-planner/config.js""
cat "sbo-rebirth-planner/config.js"
echo "Exit Code: $?"
echo ""
echo ">>> Command: ls -F "sbo-rebirth-planner/""
ls -F "sbo-rebirth-planner/"
echo "Exit Code: $?"
echo ""
echo ">>> Command: grep -r "window.SBO_AI_CONFIG" "sbo-rebirth-planner/""
grep -r "window.SBO_AI_CONFIG" "sbo-rebirth-planner/"
echo "Exit Code: $?"
echo ""
echo ">>> Command: cat "sbo-rebirth-planner/test_edge_function.js""
cat "sbo-rebirth-planner/test_edge_function.js"
echo "Exit Code: $?"
echo ""