// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as FetchWikiCandidateProcedure from "../fetch_wiki_candidate_procedure";

export type FetchWikiCandidateArgs = __Infer<typeof FetchWikiCandidateProcedure.params>;
export type FetchWikiCandidateResult = __Infer<typeof FetchWikiCandidateProcedure.returnType>;

