// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ApplyDatasetVersionUpdateReducer from "../apply_dataset_version_update_reducer";
import CompleteGuestImportReducer from "../complete_guest_import_reducer";
import ConfigureAuthReducer from "../configure_auth_reducer";
import CreateBuildShareReducer from "../create_build_share_reducer";
import CreateReleaseDraftReducer from "../create_release_draft_reducer";
import CreateReleaseDraftFromCurrentReducer from "../create_release_draft_from_current_reducer";
import DeleteBuildReducer from "../delete_build_reducer";
import DeleteDatasetReviewReducer from "../delete_dataset_review_reducer";
import DeletePlanProgressReducer from "../delete_plan_progress_reducer";
import GrantCuratorReducer from "../grant_curator_reducer";
import PublishCatalogReleaseReducer from "../publish_catalog_release_reducer";
import PublishReleaseReducer from "../publish_release_reducer";
import RecordReviewDecisionReducer from "../record_review_decision_reducer";
import RemoveDraftEquipmentReducer from "../remove_draft_equipment_reducer";
import RenameBuildReducer from "../rename_build_reducer";
import RestoreBuildRevisionReducer from "../restore_build_revision_reducer";
import RevokeBuildShareReducer from "../revoke_build_share_reducer";
import RevokeCuratorReducer from "../revoke_curator_reducer";
import SaveBuildRevisionReducer from "../save_build_revision_reducer";
import SetBuildArchivedReducer from "../set_build_archived_reducer";
import StageWikiFixtureForLocalTestReducer from "../stage_wiki_fixture_for_local_test_reducer";
import UpsertCoverageManifestReducer from "../upsert_coverage_manifest_reducer";
import UpsertDatasetReviewReducer from "../upsert_dataset_review_reducer";
import UpsertDraftCatalogEquipmentReducer from "../upsert_draft_catalog_equipment_reducer";
import UpsertDraftEquipmentReducer from "../upsert_draft_equipment_reducer";
import UpsertDraftEquipmentAcquisitionReducer from "../upsert_draft_equipment_acquisition_reducer";
import UpsertDraftEquipmentAliasReducer from "../upsert_draft_equipment_alias_reducer";
import UpsertDraftEquipmentResistanceReducer from "../upsert_draft_equipment_resistance_reducer";
import UpsertDraftEquipmentSpecialEffectReducer from "../upsert_draft_equipment_special_effect_reducer";
import UpsertDraftFormulaReducer from "../upsert_draft_formula_reducer";
import UpsertDraftMechanicReducer from "../upsert_draft_mechanic_reducer";
import UpsertDraftSourceReferenceReducer from "../upsert_draft_source_reference_reducer";
import UpsertDraftStrategyPolicyReducer from "../upsert_draft_strategy_policy_reducer";
import UpsertPlanProgressReducer from "../upsert_plan_progress_reducer";
import UpsertUserInventoryReducer from "../upsert_user_inventory_reducer";
import UpsertUserPreferencesReducer from "../upsert_user_preferences_reducer";
import UpsertWikiPageSnapshotReducer from "../upsert_wiki_page_snapshot_reducer";

export type ApplyDatasetVersionUpdateParams = __Infer<typeof ApplyDatasetVersionUpdateReducer>;
export type CompleteGuestImportParams = __Infer<typeof CompleteGuestImportReducer>;
export type ConfigureAuthParams = __Infer<typeof ConfigureAuthReducer>;
export type CreateBuildShareParams = __Infer<typeof CreateBuildShareReducer>;
export type CreateReleaseDraftParams = __Infer<typeof CreateReleaseDraftReducer>;
export type CreateReleaseDraftFromCurrentParams = __Infer<typeof CreateReleaseDraftFromCurrentReducer>;
export type DeleteBuildParams = __Infer<typeof DeleteBuildReducer>;
export type DeleteDatasetReviewParams = __Infer<typeof DeleteDatasetReviewReducer>;
export type DeletePlanProgressParams = __Infer<typeof DeletePlanProgressReducer>;
export type GrantCuratorParams = __Infer<typeof GrantCuratorReducer>;
export type PublishCatalogReleaseParams = __Infer<typeof PublishCatalogReleaseReducer>;
export type PublishReleaseParams = __Infer<typeof PublishReleaseReducer>;
export type RecordReviewDecisionParams = __Infer<typeof RecordReviewDecisionReducer>;
export type RemoveDraftEquipmentParams = __Infer<typeof RemoveDraftEquipmentReducer>;
export type RenameBuildParams = __Infer<typeof RenameBuildReducer>;
export type RestoreBuildRevisionParams = __Infer<typeof RestoreBuildRevisionReducer>;
export type RevokeBuildShareParams = __Infer<typeof RevokeBuildShareReducer>;
export type RevokeCuratorParams = __Infer<typeof RevokeCuratorReducer>;
export type SaveBuildRevisionParams = __Infer<typeof SaveBuildRevisionReducer>;
export type SetBuildArchivedParams = __Infer<typeof SetBuildArchivedReducer>;
export type StageWikiFixtureForLocalTestParams = __Infer<typeof StageWikiFixtureForLocalTestReducer>;
export type UpsertCoverageManifestParams = __Infer<typeof UpsertCoverageManifestReducer>;
export type UpsertDatasetReviewParams = __Infer<typeof UpsertDatasetReviewReducer>;
export type UpsertDraftCatalogEquipmentParams = __Infer<typeof UpsertDraftCatalogEquipmentReducer>;
export type UpsertDraftEquipmentParams = __Infer<typeof UpsertDraftEquipmentReducer>;
export type UpsertDraftEquipmentAcquisitionParams = __Infer<typeof UpsertDraftEquipmentAcquisitionReducer>;
export type UpsertDraftEquipmentAliasParams = __Infer<typeof UpsertDraftEquipmentAliasReducer>;
export type UpsertDraftEquipmentResistanceParams = __Infer<typeof UpsertDraftEquipmentResistanceReducer>;
export type UpsertDraftEquipmentSpecialEffectParams = __Infer<typeof UpsertDraftEquipmentSpecialEffectReducer>;
export type UpsertDraftFormulaParams = __Infer<typeof UpsertDraftFormulaReducer>;
export type UpsertDraftMechanicParams = __Infer<typeof UpsertDraftMechanicReducer>;
export type UpsertDraftSourceReferenceParams = __Infer<typeof UpsertDraftSourceReferenceReducer>;
export type UpsertDraftStrategyPolicyParams = __Infer<typeof UpsertDraftStrategyPolicyReducer>;
export type UpsertPlanProgressParams = __Infer<typeof UpsertPlanProgressReducer>;
export type UpsertUserInventoryParams = __Infer<typeof UpsertUserInventoryReducer>;
export type UpsertUserPreferencesParams = __Infer<typeof UpsertUserPreferencesReducer>;
export type UpsertWikiPageSnapshotParams = __Infer<typeof UpsertWikiPageSnapshotReducer>;

