// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  releaseVersion: __t.string().name("release_version"),
  itemId: __t.string().name("item_id"),
  name: __t.string(),
  variantGroupId: __t.option(__t.string()).name("variant_group_id"),
  slot: __t.string(),
  weaponPaths: __t.string().name("weapon_paths"),
  attack: __t.option(__t.f64()),
  defense: __t.option(__t.f64()),
  dexterity: __t.option(__t.f64()),
  levelRequirement: __t.option(__t.u32()).name("level_requirement"),
  skillRequirement: __t.option(__t.u32()).name("skill_requirement"),
  verificationStatus: __t.string().name("verification_status"),
  sourceRefId: __t.string().name("source_ref_id"),
  lastReviewedAt: __t.string().name("last_reviewed_at"),
});
