// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  releaseVersion: __t.string().name("release_version"),
  itemId: __t.string().name("item_id"),
  acquisitionType: __t.string().name("acquisition_type"),
  detail: __t.string(),
  floor: __t.option(__t.u32()),
  cost: __t.option(__t.f64()),
  currency: __t.option(__t.string()),
  availability: __t.string(),
  accessType: __t.string().name("access_type"),
  sourceRefId: __t.string().name("source_ref_id"),
});
