// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.8.3 (commit 8e410d2842147bd8e5a32a9589cc00c19f7478e2).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import CompleteGuestImportReducer from "./complete_guest_import_reducer";
import ConfigureAuthReducer from "./configure_auth_reducer";
import CreateBuildShareReducer from "./create_build_share_reducer";
import CreateReleaseDraftReducer from "./create_release_draft_reducer";
import DeleteBuildReducer from "./delete_build_reducer";
import GrantCuratorReducer from "./grant_curator_reducer";
import PublishReleaseReducer from "./publish_release_reducer";
import RecordReviewDecisionReducer from "./record_review_decision_reducer";
import RemoveDraftEquipmentReducer from "./remove_draft_equipment_reducer";
import RestoreBuildRevisionReducer from "./restore_build_revision_reducer";
import RevokeBuildShareReducer from "./revoke_build_share_reducer";
import RevokeCuratorReducer from "./revoke_curator_reducer";
import SaveBuildRevisionReducer from "./save_build_revision_reducer";
import StageWikiFixtureForLocalTestReducer from "./stage_wiki_fixture_for_local_test_reducer";
import UpsertDraftEquipmentReducer from "./upsert_draft_equipment_reducer";
import UpsertDraftFormulaReducer from "./upsert_draft_formula_reducer";
import UpsertDraftSourceReferenceReducer from "./upsert_draft_source_reference_reducer";

// Import all procedure arg schemas
import * as FetchWikiCandidateProcedure from "./fetch_wiki_candidate_procedure";

// Import all table schema definitions
import DatasetReleaseRow from "./dataset_release_table";
import EquipmentRow from "./equipment_table";
import FormulaRow from "./formula_table";
import MyBuildRevisionsRow from "./my_build_revisions_table";
import MyBuildsRow from "./my_builds_table";
import MyCuratorAccessRow from "./my_curator_access_table";
import MyDraftEquipmentRow from "./my_draft_equipment_table";
import MyDraftFormulasRow from "./my_draft_formulas_table";
import MyDraftSourceReferencesRow from "./my_draft_source_references_table";
import MyProfileRow from "./my_profile_table";
import MyReleaseDraftsRow from "./my_release_drafts_table";
import MyReviewDecisionsRow from "./my_review_decisions_table";
import MyRevisionEquipmentRow from "./my_revision_equipment_table";
import MyRevisionOwnedItemsRow from "./my_revision_owned_items_table";
import MyWikiCandidatesRow from "./my_wiki_candidates_table";
import SharedBuildRow from "./shared_build_table";
import SharedBuildEquipmentRow from "./shared_build_equipment_table";
import SharedBuildOwnedItemRow from "./shared_build_owned_item_table";
import SourceReferenceRow from "./source_reference_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  datasetRelease: __table({
    name: 'dataset_release',
    indexes: [
      { accessor: 'id', name: 'dataset_release_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'version', name: 'dataset_release_version_idx_btree', algorithm: 'btree', columns: [
        'version',
      ] },
    ],
    constraints: [
      { name: 'dataset_release_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'dataset_release_version_key', constraint: 'unique', columns: ['version'] },
    ],
  }, DatasetReleaseRow),
  equipment: __table({
    name: 'equipment',
    indexes: [
      { accessor: 'id', name: 'equipment_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'equipmentReleaseVersion', name: 'equipment_release_version_idx_btree', algorithm: 'btree', columns: [
        'releaseVersion',
      ] },
    ],
    constraints: [
      { name: 'equipment_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EquipmentRow),
  formula: __table({
    name: 'formula',
    indexes: [
      { accessor: 'id', name: 'formula_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'formulaReleaseVersion', name: 'formula_release_version_idx_btree', algorithm: 'btree', columns: [
        'releaseVersion',
      ] },
    ],
    constraints: [
      { name: 'formula_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FormulaRow),
  sharedBuild: __table({
    name: 'shared_build',
    indexes: [
      { accessor: 'shareId', name: 'shared_build_share_id_idx_btree', algorithm: 'btree', columns: [
        'shareId',
      ] },
    ],
    constraints: [
      { name: 'shared_build_share_id_key', constraint: 'unique', columns: ['shareId'] },
    ],
  }, SharedBuildRow),
  sharedBuildEquipment: __table({
    name: 'shared_build_equipment',
    indexes: [
      { accessor: 'id', name: 'shared_build_equipment_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sharedBuildEquipmentShareId', name: 'shared_build_equipment_share_id_idx_btree', algorithm: 'btree', columns: [
        'shareId',
      ] },
    ],
    constraints: [
      { name: 'shared_build_equipment_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SharedBuildEquipmentRow),
  sharedBuildOwnedItem: __table({
    name: 'shared_build_owned_item',
    indexes: [
      { accessor: 'id', name: 'shared_build_owned_item_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sharedBuildOwnedItemShareId', name: 'shared_build_owned_item_share_id_idx_btree', algorithm: 'btree', columns: [
        'shareId',
      ] },
    ],
    constraints: [
      { name: 'shared_build_owned_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SharedBuildOwnedItemRow),
  sourceReference: __table({
    name: 'source_reference',
    indexes: [
      { accessor: 'id', name: 'source_reference_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sourceReferenceReleaseVersion', name: 'source_reference_release_version_idx_btree', algorithm: 'btree', columns: [
        'releaseVersion',
      ] },
    ],
    constraints: [
      { name: 'source_reference_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SourceReferenceRow),
  myBuildRevisions: __table({
    name: 'my_build_revisions',
    indexes: [
    ],
    constraints: [
    ],
  }, MyBuildRevisionsRow),
  myBuilds: __table({
    name: 'my_builds',
    indexes: [
    ],
    constraints: [
    ],
  }, MyBuildsRow),
  myCuratorAccess: __table({
    name: 'my_curator_access',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCuratorAccessRow),
  myDraftEquipment: __table({
    name: 'my_draft_equipment',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDraftEquipmentRow),
  myDraftFormulas: __table({
    name: 'my_draft_formulas',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDraftFormulasRow),
  myDraftSourceReferences: __table({
    name: 'my_draft_source_references',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDraftSourceReferencesRow),
  myProfile: __table({
    name: 'my_profile',
    indexes: [
    ],
    constraints: [
    ],
  }, MyProfileRow),
  myReleaseDrafts: __table({
    name: 'my_release_drafts',
    indexes: [
    ],
    constraints: [
    ],
  }, MyReleaseDraftsRow),
  myReviewDecisions: __table({
    name: 'my_review_decisions',
    indexes: [
    ],
    constraints: [
    ],
  }, MyReviewDecisionsRow),
  myRevisionEquipment: __table({
    name: 'my_revision_equipment',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRevisionEquipmentRow),
  myRevisionOwnedItems: __table({
    name: 'my_revision_owned_items',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRevisionOwnedItemsRow),
  myWikiCandidates: __table({
    name: 'my_wiki_candidates',
    indexes: [
    ],
    constraints: [
    ],
  }, MyWikiCandidatesRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("complete_guest_import", CompleteGuestImportReducer),
  __reducerSchema("configure_auth", ConfigureAuthReducer),
  __reducerSchema("create_build_share", CreateBuildShareReducer),
  __reducerSchema("create_release_draft", CreateReleaseDraftReducer),
  __reducerSchema("delete_build", DeleteBuildReducer),
  __reducerSchema("grant_curator", GrantCuratorReducer),
  __reducerSchema("publish_release", PublishReleaseReducer),
  __reducerSchema("record_review_decision", RecordReviewDecisionReducer),
  __reducerSchema("remove_draft_equipment", RemoveDraftEquipmentReducer),
  __reducerSchema("restore_build_revision", RestoreBuildRevisionReducer),
  __reducerSchema("revoke_build_share", RevokeBuildShareReducer),
  __reducerSchema("revoke_curator", RevokeCuratorReducer),
  __reducerSchema("save_build_revision", SaveBuildRevisionReducer),
  __reducerSchema("stage_wiki_fixture_for_local_test", StageWikiFixtureForLocalTestReducer),
  __reducerSchema("upsert_draft_equipment", UpsertDraftEquipmentReducer),
  __reducerSchema("upsert_draft_formula", UpsertDraftFormulaReducer),
  __reducerSchema("upsert_draft_source_reference", UpsertDraftSourceReferenceReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("fetch_wiki_candidate", FetchWikiCandidateProcedure.params, FetchWikiCandidateProcedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.8.3" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

