// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  buildId: __t.string().name("build_id"),
  owner: __t.identity(),
  parentRevisionId: __t.option(__t.string()).name("parent_revision_id"),
  schemaVersion: __t.u32().name("schema_version"),
  level: __t.u32(),
  maxFloor: __t.u32().name("max_floor"),
  weaponPath: __t.string().name("weapon_path"),
  goal: __t.string(),
  weaponSkill: __t.option(__t.u32()).name("weapon_skill"),
  str: __t.u32(),
  def: __t.u32(),
  agi: __t.u32(),
  vit: __t.u32(),
  luk: __t.u32(),
  datasetVersion: __t.string().name("dataset_version"),
  accessPreferences: __t.option(__t.string()).name("access_preferences"),
  createdAt: __t.timestamp().name("created_at"),
});
