// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  releaseVersion: __t.string().primaryKey().name("release_version"),
  discovered: __t.u32(),
  fetched: __t.u32(),
  parsed: __t.u32(),
  normalized: __t.u32(),
  verified: __t.u32(),
  partial: __t.u32(),
  conflicting: __t.u32(),
  unknown: __t.u32(),
  legacy: __t.u32(),
  unresolvedJson: __t.string().name("unresolved_json"),
  manifestHash: __t.string().name("manifest_hash"),
  createdAt: __t.timestamp().name("created_at"),
});
