// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  releaseVersion: __t.string().primaryKey().name("release_version"),
  policyVersion: __t.string().name("policy_version"),
  policyJson: __t.string().name("policy_json"),
  lastReviewedAt: __t.string().name("last_reviewed_at"),
});
