// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  releaseVersion: __t.string().name("release_version"),
  mechanicId: __t.string().name("mechanic_id"),
  expression: __t.string(),
  units: __t.string(),
  applicability: __t.string(),
  boundaryBehavior: __t.string().name("boundary_behavior"),
  computability: __t.string(),
  parametersJson: __t.string().name("parameters_json"),
  verificationStatus: __t.string().name("verification_status"),
  sourceRefId: __t.string().name("source_ref_id"),
  lastReviewedAt: __t.string().name("last_reviewed_at"),
  candidateId: __t.string().name("candidate_id"),
});
