// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  version: __t.string().primaryKey(),
  createdBy: __t.identity().name("created_by"),
  formulaSetVersion: __t.string().name("formula_set_version"),
  sourceSummary: __t.string().name("source_summary"),
  lastReviewedAt: __t.string().name("last_reviewed_at"),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
