// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  pageId: __t.u64().name("page_id"),
  pageTitle: __t.string().name("page_title"),
  sourceUrl: __t.string().name("source_url"),
  revisionId: __t.string().name("revision_id"),
  revisionTimestamp: __t.string().name("revision_timestamp"),
  contentHash: __t.string().name("content_hash"),
  redirectTarget: __t.option(__t.string()).name("redirect_target"),
  content: __t.string(),
  fetchedAt: __t.timestamp().name("fetched_at"),
});
