// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  CloudProfileInput,
  CloudEquipmentInput,
} from "./types";

export default {
  buildId: __t.string(),
  revisionId: __t.string(),
  name: __t.string(),
  kind: __t.option(__t.string()),
  parentRevisionId: __t.option(__t.string()),
  get profile() {
    return CloudProfileInput;
  },
  get equipment() {
    return __t.array(CloudEquipmentInput);
  },
  ownedItemIds: __t.array(__t.string()),
};
