// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  releaseVersion: __t.string().name("release_version"),
  entityKind: __t.string().name("entity_kind"),
  entityId: __t.string().name("entity_id"),
  sourceUrl: __t.string().name("source_url"),
  sourceRevision: __t.string().name("source_revision"),
  capturedAt: __t.string().name("captured_at"),
  lastReviewedAt: __t.string().name("last_reviewed_at"),
  candidateId: __t.option(__t.string()).name("candidate_id"),
});
