// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AppConfig = __t.object("AppConfig", {
  ownerIdentity: __t.identity(),
});
export type AppConfig = __Infer<typeof AppConfig>;

export const DatasetRelease = __t.object("DatasetRelease", {
  id: __t.u64(),
  version: __t.string(),
  formulaSetVersion: __t.string(),
  publishedAt: __t.timestamp(),
  lastReviewedAt: __t.string(),
  sourceSummary: __t.string(),
  isCurrent: __t.bool(),
});
export type DatasetRelease = __Infer<typeof DatasetRelease>;

