// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AppConfig = __t.object("AppConfig", {
  ownerIdentity: __t.identity(),
});
export type AppConfig = __Infer<typeof AppConfig>;

export const AuthConfig = __t.object("AuthConfig", {
  key: __t.string(),
  mode: __t.string(),
  issuer: __t.string(),
  audience: __t.string(),
});
export type AuthConfig = __Infer<typeof AuthConfig>;

export const Build = __t.object("Build", {
  id: __t.string(),
  owner: __t.identity(),
  name: __t.string(),
  headRevisionId: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  archivedAt: __t.option(__t.timestamp()),
});
export type Build = __Infer<typeof Build>;

export const BuildPlanProgress = __t.object("BuildPlanProgress", {
  buildId: __t.string(),
  owner: __t.identity(),
  progressJson: __t.string(),
  updatedAt: __t.timestamp(),
});
export type BuildPlanProgress = __Infer<typeof BuildPlanProgress>;

export const BuildRevision = __t.object("BuildRevision", {
  id: __t.string(),
  buildId: __t.string(),
  owner: __t.identity(),
  parentRevisionId: __t.option(__t.string()),
  schemaVersion: __t.u32(),
  level: __t.u32(),
  maxFloor: __t.u32(),
  weaponPath: __t.string(),
  goal: __t.string(),
  weaponSkill: __t.option(__t.u32()),
  str: __t.u32(),
  def: __t.u32(),
  agi: __t.u32(),
  vit: __t.u32(),
  luk: __t.u32(),
  datasetVersion: __t.string(),
  createdAt: __t.timestamp(),
  accessPreferences: __t.option(__t.string()),
});
export type BuildRevision = __Infer<typeof BuildRevision>;

export const BuildShareOwner = __t.object("BuildShareOwner", {
  shareId: __t.string(),
  owner: __t.identity(),
  buildId: __t.string(),
  createdAt: __t.timestamp(),
});
export type BuildShareOwner = __Infer<typeof BuildShareOwner>;

export const CatalogEquipment = __t.object("CatalogEquipment", {
  id: __t.string(),
  releaseVersion: __t.string(),
  itemId: __t.string(),
  name: __t.string(),
  variantGroupId: __t.option(__t.string()),
  slot: __t.string(),
  weaponPaths: __t.string(),
  attack: __t.option(__t.f64()),
  defense: __t.option(__t.f64()),
  dexterity: __t.option(__t.f64()),
  levelRequirement: __t.option(__t.u32()),
  skillRequirement: __t.option(__t.u32()),
  verificationStatus: __t.string(),
  sourceRefId: __t.string(),
  lastReviewedAt: __t.string(),
});
export type CatalogEquipment = __Infer<typeof CatalogEquipment>;

export const CloudEquipmentInput = __t.object("CloudEquipmentInput", {
  slot: __t.string(),
  itemId: __t.string(),
});
export type CloudEquipmentInput = __Infer<typeof CloudEquipmentInput>;

export const CloudProfileInput = __t.object("CloudProfileInput", {
  schemaVersion: __t.u32(),
  level: __t.u32(),
  maxFloor: __t.u32(),
  weaponPath: __t.string(),
  goal: __t.string(),
  weaponSkill: __t.option(__t.u32()),
  str: __t.u32(),
  def: __t.u32(),
  agi: __t.u32(),
  vit: __t.u32(),
  luk: __t.u32(),
  datasetVersion: __t.string(),
  accessPreferences: __t.option(__t.string()),
});
export type CloudProfileInput = __Infer<typeof CloudProfileInput>;

export const CoverageManifest = __t.object("CoverageManifest", {
  releaseVersion: __t.string(),
  discovered: __t.u32(),
  fetched: __t.u32(),
  parsed: __t.u32(),
  normalized: __t.u32(),
  verified: __t.u32(),
  partial: __t.u32(),
  conflicting: __t.u32(),
  unknown: __t.u32(),
  legacy: __t.u32(),
  unresolvedJson: __t.string(),
  manifestHash: __t.string(),
  createdAt: __t.timestamp(),
});
export type CoverageManifest = __Infer<typeof CoverageManifest>;

export const CuratorAccess = __t.object("CuratorAccess", {
  identity: __t.identity(),
  access: __t.string(),
});
export type CuratorAccess = __Infer<typeof CuratorAccess>;

export const CuratorRole = __t.object("CuratorRole", {
  identity: __t.identity(),
  grantedBy: __t.identity(),
  grantedAt: __t.timestamp(),
});
export type CuratorRole = __Infer<typeof CuratorRole>;

export const DatasetRelease = __t.object("DatasetRelease", {
  id: __t.u64(),
  version: __t.string(),
  formulaSetVersion: __t.string(),
  publishedAt: __t.timestamp(),
  lastReviewedAt: __t.string(),
  sourceSummary: __t.string(),
  isCurrent: __t.bool(),
});
export type DatasetRelease = __Infer<typeof DatasetRelease>;

export const DraftCatalogEquipment = __t.object("DraftCatalogEquipment", {
  id: __t.string(),
  releaseVersion: __t.string(),
  itemId: __t.string(),
  name: __t.string(),
  variantGroupId: __t.option(__t.string()),
  slot: __t.string(),
  weaponPaths: __t.string(),
  attack: __t.option(__t.f64()),
  defense: __t.option(__t.f64()),
  dexterity: __t.option(__t.f64()),
  levelRequirement: __t.option(__t.u32()),
  skillRequirement: __t.option(__t.u32()),
  verificationStatus: __t.string(),
  sourceRefId: __t.string(),
  lastReviewedAt: __t.string(),
  candidateId: __t.string(),
});
export type DraftCatalogEquipment = __Infer<typeof DraftCatalogEquipment>;

export const DraftEquipment = __t.object("DraftEquipment", {
  id: __t.string(),
  releaseVersion: __t.string(),
  itemId: __t.string(),
  name: __t.string(),
  slot: __t.string(),
  weaponPaths: __t.string(),
  attack: __t.f64(),
  defense: __t.f64(),
  dexterity: __t.f64(),
  levelRequirement: __t.u32(),
  skillRequirement: __t.option(__t.u32()),
  floor: __t.u32(),
  acquisitionType: __t.string(),
  acquisitionDetail: __t.string(),
  availability: __t.string(),
  sourceRefId: __t.string(),
  lastReviewedAt: __t.string(),
  candidateId: __t.string(),
});
export type DraftEquipment = __Infer<typeof DraftEquipment>;

export const DraftEquipmentAcquisition = __t.object("DraftEquipmentAcquisition", {
  id: __t.string(),
  releaseVersion: __t.string(),
  itemId: __t.string(),
  acquisitionType: __t.string(),
  detail: __t.string(),
  floor: __t.option(__t.u32()),
  cost: __t.option(__t.f64()),
  currency: __t.option(__t.string()),
  availability: __t.string(),
  accessType: __t.string(),
  sourceRefId: __t.string(),
  candidateId: __t.string(),
});
export type DraftEquipmentAcquisition = __Infer<typeof DraftEquipmentAcquisition>;

export const DraftEquipmentAlias = __t.object("DraftEquipmentAlias", {
  id: __t.string(),
  releaseVersion: __t.string(),
  itemId: __t.string(),
  alias: __t.string(),
  sourceRefId: __t.string(),
  candidateId: __t.string(),
});
export type DraftEquipmentAlias = __Infer<typeof DraftEquipmentAlias>;

export const DraftEquipmentResistance = __t.object("DraftEquipmentResistance", {
  id: __t.string(),
  releaseVersion: __t.string(),
  itemId: __t.string(),
  status: __t.string(),
  percent: __t.f64(),
  sourceRefId: __t.string(),
  candidateId: __t.string(),
});
export type DraftEquipmentResistance = __Infer<typeof DraftEquipmentResistance>;

export const DraftEquipmentSpecialEffect = __t.object("DraftEquipmentSpecialEffect", {
  id: __t.string(),
  releaseVersion: __t.string(),
  itemId: __t.string(),
  description: __t.string(),
  sourceRefId: __t.string(),
  candidateId: __t.string(),
});
export type DraftEquipmentSpecialEffect = __Infer<typeof DraftEquipmentSpecialEffect>;

export const DraftFormula = __t.object("DraftFormula", {
  id: __t.string(),
  releaseVersion: __t.string(),
  formulaId: __t.string(),
  expression: __t.string(),
  units: __t.string(),
  applicability: __t.string(),
  boundaryBehavior: __t.string(),
  sourceRefId: __t.string(),
  lastReviewedAt: __t.string(),
  candidateId: __t.string(),
});
export type DraftFormula = __Infer<typeof DraftFormula>;

export const DraftMechanic = __t.object("DraftMechanic", {
  id: __t.string(),
  releaseVersion: __t.string(),
  mechanicId: __t.string(),
  expression: __t.string(),
  units: __t.string(),
  applicability: __t.string(),
  boundaryBehavior: __t.string(),
  computability: __t.string(),
  parametersJson: __t.string(),
  verificationStatus: __t.string(),
  sourceRefId: __t.string(),
  lastReviewedAt: __t.string(),
  candidateId: __t.string(),
});
export type DraftMechanic = __Infer<typeof DraftMechanic>;

export const DraftSourceReference = __t.object("DraftSourceReference", {
  id: __t.string(),
  releaseVersion: __t.string(),
  entityKind: __t.string(),
  entityId: __t.string(),
  sourceUrl: __t.string(),
  sourceRevision: __t.string(),
  capturedAt: __t.string(),
  lastReviewedAt: __t.string(),
  candidateId: __t.string(),
});
export type DraftSourceReference = __Infer<typeof DraftSourceReference>;

export const DraftStrategyPolicy = __t.object("DraftStrategyPolicy", {
  releaseVersion: __t.string(),
  policyVersion: __t.string(),
  policyJson: __t.string(),
  lastReviewedAt: __t.string(),
});
export type DraftStrategyPolicy = __Infer<typeof DraftStrategyPolicy>;

export const Equipment = __t.object("Equipment", {
  id: __t.string(),
  releaseVersion: __t.string(),
  itemId: __t.string(),
  name: __t.string(),
  slot: __t.string(),
  weaponPaths: __t.string(),
  attack: __t.f64(),
  defense: __t.f64(),
  dexterity: __t.f64(),
  levelRequirement: __t.u32(),
  skillRequirement: __t.option(__t.u32()),
  floor: __t.u32(),
  acquisitionType: __t.string(),
  acquisitionDetail: __t.string(),
  availability: __t.string(),
  sourceRefId: __t.string(),
  lastReviewedAt: __t.string(),
});
export type Equipment = __Infer<typeof Equipment>;

export const EquipmentAcquisition = __t.object("EquipmentAcquisition", {
  id: __t.string(),
  releaseVersion: __t.string(),
  itemId: __t.string(),
  acquisitionType: __t.string(),
  detail: __t.string(),
  floor: __t.option(__t.u32()),
  cost: __t.option(__t.f64()),
  currency: __t.option(__t.string()),
  availability: __t.string(),
  accessType: __t.string(),
  sourceRefId: __t.string(),
});
export type EquipmentAcquisition = __Infer<typeof EquipmentAcquisition>;

export const EquipmentAlias = __t.object("EquipmentAlias", {
  id: __t.string(),
  releaseVersion: __t.string(),
  itemId: __t.string(),
  alias: __t.string(),
  sourceRefId: __t.string(),
});
export type EquipmentAlias = __Infer<typeof EquipmentAlias>;

export const EquipmentResistance = __t.object("EquipmentResistance", {
  id: __t.string(),
  releaseVersion: __t.string(),
  itemId: __t.string(),
  status: __t.string(),
  percent: __t.f64(),
  sourceRefId: __t.string(),
});
export type EquipmentResistance = __Infer<typeof EquipmentResistance>;

export const EquipmentSpecialEffect = __t.object("EquipmentSpecialEffect", {
  id: __t.string(),
  releaseVersion: __t.string(),
  itemId: __t.string(),
  description: __t.string(),
  sourceRefId: __t.string(),
});
export type EquipmentSpecialEffect = __Infer<typeof EquipmentSpecialEffect>;

export const Formula = __t.object("Formula", {
  id: __t.string(),
  releaseVersion: __t.string(),
  formulaId: __t.string(),
  expression: __t.string(),
  units: __t.string(),
  applicability: __t.string(),
  boundaryBehavior: __t.string(),
  sourceRefId: __t.string(),
  lastReviewedAt: __t.string(),
});
export type Formula = __Infer<typeof Formula>;

export const Mechanic = __t.object("Mechanic", {
  id: __t.string(),
  releaseVersion: __t.string(),
  mechanicId: __t.string(),
  expression: __t.string(),
  units: __t.string(),
  applicability: __t.string(),
  boundaryBehavior: __t.string(),
  computability: __t.string(),
  parametersJson: __t.string(),
  verificationStatus: __t.string(),
  sourceRefId: __t.string(),
  lastReviewedAt: __t.string(),
});
export type Mechanic = __Infer<typeof Mechanic>;

export const MyBuildRevisions = __t.object("MyBuildRevisions", {});
export type MyBuildRevisions = __Infer<typeof MyBuildRevisions>;

export const MyBuilds = __t.object("MyBuilds", {});
export type MyBuilds = __Infer<typeof MyBuilds>;

export const MyCoverageManifests = __t.object("MyCoverageManifests", {});
export type MyCoverageManifests = __Infer<typeof MyCoverageManifests>;

export const MyCuratorAccess = __t.object("MyCuratorAccess", {});
export type MyCuratorAccess = __Infer<typeof MyCuratorAccess>;

export const MyDraftCatalogEquipment = __t.object("MyDraftCatalogEquipment", {});
export type MyDraftCatalogEquipment = __Infer<typeof MyDraftCatalogEquipment>;

export const MyDraftEquipment = __t.object("MyDraftEquipment", {});
export type MyDraftEquipment = __Infer<typeof MyDraftEquipment>;

export const MyDraftEquipmentAcquisitions = __t.object("MyDraftEquipmentAcquisitions", {});
export type MyDraftEquipmentAcquisitions = __Infer<typeof MyDraftEquipmentAcquisitions>;

export const MyDraftEquipmentAliases = __t.object("MyDraftEquipmentAliases", {});
export type MyDraftEquipmentAliases = __Infer<typeof MyDraftEquipmentAliases>;

export const MyDraftEquipmentResistances = __t.object("MyDraftEquipmentResistances", {});
export type MyDraftEquipmentResistances = __Infer<typeof MyDraftEquipmentResistances>;

export const MyDraftEquipmentSpecialEffects = __t.object("MyDraftEquipmentSpecialEffects", {});
export type MyDraftEquipmentSpecialEffects = __Infer<typeof MyDraftEquipmentSpecialEffects>;

export const MyDraftFormulas = __t.object("MyDraftFormulas", {});
export type MyDraftFormulas = __Infer<typeof MyDraftFormulas>;

export const MyDraftMechanics = __t.object("MyDraftMechanics", {});
export type MyDraftMechanics = __Infer<typeof MyDraftMechanics>;

export const MyDraftSourceReferences = __t.object("MyDraftSourceReferences", {});
export type MyDraftSourceReferences = __Infer<typeof MyDraftSourceReferences>;

export const MyDraftStrategyPolicies = __t.object("MyDraftStrategyPolicies", {});
export type MyDraftStrategyPolicies = __Infer<typeof MyDraftStrategyPolicies>;

export const MyPlanProgress = __t.object("MyPlanProgress", {});
export type MyPlanProgress = __Infer<typeof MyPlanProgress>;

export const MyProfile = __t.object("MyProfile", {});
export type MyProfile = __Infer<typeof MyProfile>;

export const MyReleaseDrafts = __t.object("MyReleaseDrafts", {});
export type MyReleaseDrafts = __Infer<typeof MyReleaseDrafts>;

export const MyReviewDecisions = __t.object("MyReviewDecisions", {});
export type MyReviewDecisions = __Infer<typeof MyReviewDecisions>;

export const MyRevisionEquipment = __t.object("MyRevisionEquipment", {});
export type MyRevisionEquipment = __Infer<typeof MyRevisionEquipment>;

export const MyRevisionOwnedItems = __t.object("MyRevisionOwnedItems", {});
export type MyRevisionOwnedItems = __Infer<typeof MyRevisionOwnedItems>;

export const MyUserInventory = __t.object("MyUserInventory", {});
export type MyUserInventory = __Infer<typeof MyUserInventory>;

export const MyUserPreferences = __t.object("MyUserPreferences", {});
export type MyUserPreferences = __Infer<typeof MyUserPreferences>;

export const MyWikiCandidates = __t.object("MyWikiCandidates", {});
export type MyWikiCandidates = __Infer<typeof MyWikiCandidates>;

export const MyWikiPageSnapshots = __t.object("MyWikiPageSnapshots", {});
export type MyWikiPageSnapshots = __Infer<typeof MyWikiPageSnapshots>;

export const ReleaseDraft = __t.object("ReleaseDraft", {
  version: __t.string(),
  createdBy: __t.identity(),
  formulaSetVersion: __t.string(),
  sourceSummary: __t.string(),
  lastReviewedAt: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ReleaseDraft = __Infer<typeof ReleaseDraft>;

export const ReleaseStrategyPolicy = __t.object("ReleaseStrategyPolicy", {
  releaseVersion: __t.string(),
  policyVersion: __t.string(),
  policyJson: __t.string(),
  lastReviewedAt: __t.string(),
});
export type ReleaseStrategyPolicy = __Infer<typeof ReleaseStrategyPolicy>;

export const ReviewDecision = __t.object("ReviewDecision", {
  id: __t.string(),
  candidateId: __t.string(),
  curator: __t.identity(),
  decision: __t.string(),
  note: __t.string(),
  createdAt: __t.timestamp(),
});
export type ReviewDecision = __Infer<typeof ReviewDecision>;

export const RevisionEquipment = __t.object("RevisionEquipment", {
  id: __t.string(),
  revisionId: __t.string(),
  owner: __t.identity(),
  slot: __t.string(),
  itemId: __t.string(),
});
export type RevisionEquipment = __Infer<typeof RevisionEquipment>;

export const RevisionOwnedItem = __t.object("RevisionOwnedItem", {
  id: __t.string(),
  revisionId: __t.string(),
  owner: __t.identity(),
  itemId: __t.string(),
});
export type RevisionOwnedItem = __Infer<typeof RevisionOwnedItem>;

export const SharedBuild = __t.object("SharedBuild", {
  shareId: __t.string(),
  name: __t.string(),
  schemaVersion: __t.u32(),
  level: __t.u32(),
  maxFloor: __t.u32(),
  weaponPath: __t.string(),
  goal: __t.string(),
  weaponSkill: __t.option(__t.u32()),
  str: __t.u32(),
  def: __t.u32(),
  agi: __t.u32(),
  vit: __t.u32(),
  luk: __t.u32(),
  datasetVersion: __t.string(),
  createdAt: __t.timestamp(),
  accessPreferences: __t.option(__t.string()),
});
export type SharedBuild = __Infer<typeof SharedBuild>;

export const SharedBuildEquipment = __t.object("SharedBuildEquipment", {
  id: __t.string(),
  shareId: __t.string(),
  slot: __t.string(),
  itemId: __t.string(),
});
export type SharedBuildEquipment = __Infer<typeof SharedBuildEquipment>;

export const SharedBuildOwnedItem = __t.object("SharedBuildOwnedItem", {
  id: __t.string(),
  shareId: __t.string(),
  itemId: __t.string(),
});
export type SharedBuildOwnedItem = __Infer<typeof SharedBuildOwnedItem>;

export const SourceReference = __t.object("SourceReference", {
  id: __t.string(),
  releaseVersion: __t.string(),
  entityKind: __t.string(),
  entityId: __t.string(),
  sourceUrl: __t.string(),
  sourceRevision: __t.string(),
  capturedAt: __t.string(),
  lastReviewedAt: __t.string(),
  candidateId: __t.string(),
});
export type SourceReference = __Infer<typeof SourceReference>;

export const UserInventory = __t.object("UserInventory", {
  identity: __t.identity(),
  inventoryJson: __t.string(),
  updatedAt: __t.timestamp(),
});
export type UserInventory = __Infer<typeof UserInventory>;

export const UserPreference = __t.object("UserPreference", {
  identity: __t.identity(),
  preferencesJson: __t.string(),
  updatedAt: __t.timestamp(),
});
export type UserPreference = __Infer<typeof UserPreference>;

export const UserProfile = __t.object("UserProfile", {
  identity: __t.identity(),
  guestImportCompletedAt: __t.option(__t.timestamp()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type UserProfile = __Infer<typeof UserProfile>;

export const WikiCandidate = __t.object("WikiCandidate", {
  id: __t.string(),
  pageTitle: __t.string(),
  sourceUrl: __t.string(),
  revisionId: __t.string(),
  revisionTimestamp: __t.string(),
  content: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type WikiCandidate = __Infer<typeof WikiCandidate>;

export const WikiCheckJob = __t.object("WikiCheckJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  pageTitle: __t.string(),
});
export type WikiCheckJob = __Infer<typeof WikiCheckJob>;

export const WikiPageSnapshot = __t.object("WikiPageSnapshot", {
  id: __t.string(),
  pageId: __t.u64(),
  pageTitle: __t.string(),
  sourceUrl: __t.string(),
  revisionId: __t.string(),
  revisionTimestamp: __t.string(),
  contentHash: __t.string(),
  redirectTarget: __t.option(__t.string()),
  content: __t.string(),
  fetchedAt: __t.timestamp(),
});
export type WikiPageSnapshot = __Infer<typeof WikiPageSnapshot>;

export const WikiSourceState = __t.object("WikiSourceState", {
  pageTitle: __t.string(),
  lastRevisionId: __t.string(),
  lastCheckedAt: __t.timestamp(),
});
export type WikiSourceState = __Infer<typeof WikiSourceState>;

