// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  releaseVersion: __t.string(),
  itemId: __t.string(),
  acquisitionType: __t.string(),
  detail: __t.string(),
  floor: __t.option(__t.u32()),
  cost: __t.option(__t.f64()),
  currency: __t.option(__t.string()),
  availability: __t.string(),
  accessType: __t.string(),
  sourceRefId: __t.string(),
  candidateId: __t.string(),
};
