// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  releaseVersion: __t.string(),
  itemId: __t.string(),
  name: __t.string(),
  slot: __t.string(),
  weaponPaths: __t.string(),
  attack: __t.f64(),
  defense: __t.f64(),
  dexterity: __t.f64(),
  levelRequirement: __t.u32(),
  skillRequirement: __t.option(__t.u32()),
  floor: __t.u32(),
  acquisitionType: __t.string(),
  acquisitionDetail: __t.string(),
  availability: __t.string(),
  sourceRefId: __t.string(),
  lastReviewedAt: __t.string(),
  candidateId: __t.string(),
};
