// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  releaseVersion: __t.string(),
  entityKind: __t.string(),
  entityId: __t.string(),
  sourceUrl: __t.string(),
  sourceRevision: __t.string(),
  capturedAt: __t.string(),
  lastReviewedAt: __t.string(),
  candidateId: __t.string(),
};
