// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  releaseVersion: __t.string(),
  itemId: __t.string(),
  name: __t.string(),
  variantGroupId: __t.option(__t.string()),
  slot: __t.string(),
  weaponPaths: __t.string(),
  attack: __t.option(__t.f64()),
  defense: __t.option(__t.f64()),
  dexterity: __t.option(__t.f64()),
  levelRequirement: __t.option(__t.u32()),
  skillRequirement: __t.option(__t.u32()),
  verificationStatus: __t.string(),
  sourceRefId: __t.string(),
  lastReviewedAt: __t.string(),
  candidateId: __t.string(),
};
