// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const MyPlannerDocs = __t.object("MyPlannerDocs", {});
export type MyPlannerDocs = __Infer<typeof MyPlannerDocs>;

export const PlannerDoc = __t.object("PlannerDoc", {
  id: __t.u64(),
  owner: __t.identity(),
  docKey: __t.string(),
  docJson: __t.string(),
  updatedAt: __t.timestamp(),
});
export type PlannerDoc = __Infer<typeof PlannerDoc>;

export const PlannerDocRow = __t.object("PlannerDocRow", {
  id: __t.u64(),
  owner: __t.identity(),
  docKey: __t.string(),
  docJson: __t.string(),
  updatedAt: __t.timestamp(),
});
export type PlannerDocRow = __Infer<typeof PlannerDocRow>;

